package de.seuhd.campuscoffee.api.mapper

import de.seuhd.campuscoffee.api.dtos.ReviewDto
import de.seuhd.campuscoffee.domain.model.objects.Review
import de.seuhd.campuscoffee.domain.model.objects.User
import de.seuhd.campuscoffee.domain.ports.api.PosService
import org.mapstruct.Mapper
import org.mapstruct.Mapping
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean

/**
 * Mapper between the [Review] domain model and [ReviewDto]. `fromDomain` is generated by MapStruct from
 * the `@Mapping`s below; `toDomain` is handwritten because it resolves the referenced POS, sets the
 * author from the authenticated user (never from the request body), and resets the approval state.
 */
@Mapper(componentModel = "spring")
@ConditionalOnMissingBean // prevent IntelliJ warning about duplicate beans
abstract class ReviewDtoMapper : DtoMapper<Review, ReviewDto> {
    // internal, not protected: MapStruct's generated subclass and the same-module test both inject these,
    // and a protected member is not visible to a test in the same package
    @Autowired
    internal lateinit var posService: PosService

    @Mapping(target = "posId", source = "pos.id")
    @Mapping(target = "authorId", source = "author.id")
    abstract override fun fromDomain(source: Review): ReviewDto

    /**
     * The [DtoMapper] contract requires a single-argument `toDomain`, but a review's author is the
     * authenticated user (resolved from the request principal), not a field of the DTO -- there is no
     * author to supply here. This overload is therefore unsupported; the controller builds a review with
     * the [toDomain] overload that takes the explicit author instead.
     */
    override fun toDomain(source: ReviewDto): Review =
        throw UnsupportedOperationException(
            "A review's author is the authenticated user; use toDomain(source, author)."
        )

    /**
     * Builds a domain review from the DTO, resolving the referenced POS by id and taking the author from
     * the authenticated [author]. The DTO's `authorId` is ignored (it is rejected on input) and its
     * `approved` value is reset: a new review starts unapproved with a zero approval count, and on an
     * update the service restores the persisted approval state (approvals are owned by the approval
     * workflow, never by the client).
     *
     * TODO (Exercise 2): the author is the authenticated user, not the DTO's authorId; the controller must
     *  supply it (and a body carrying an authorId is rejected). Adjust how the author is resolved here.
     */
    fun toDomain(
        source: ReviewDto,
        author: User
    ): Review =
        Review(
            id = source.id,
            createdAt = source.createdAt,
            updatedAt = source.updatedAt,
            pos = posService.getById(source.posId!!),
            author = author,
            review = source.review!!,
            approved = false,
            approvalCount = 0
        )
}
